name: Laboratory CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 1. 코드 체크아웃
        uses: actions/checkout@v3

      - name: 2. JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Gradle 빌드
        run: ./gradlew clean build -x test

      - name: 4. JAR 복사
        run: |
          cp build/libs/*.jar /home/github-runner/app/app.jar

      - name: 5. Spring Boot 서비스 재시작
        run: |
          sudo systemctl restart spring-app
